version: '3'
services:
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: nginx_container
        restart: unless-stopped
        tty: true
        ports:
          - "9090:80"
          - "9093:443"
        volumes:
          - .:/var/www/
          - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
          - app

    #PHP Service
    app:
        build: .docker/php
        container_name: app_container
        volumes:
          - .:/var/www/
          - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        restart: unless-stopped
        tty: true
#        environment:
#          - maildev_host=maildev_container
            #SERVICE_NAME: app
            #SERVICE_TAGS: dev
        working_dir: /var/www
#        depends_on:
#          - maildev
#          - mysql

    #MySQL Service
#    mysql:
#        image: mysql:8
#        container_name: mysql_container
#        volumes:
#            - .docker/data/db:/var/lib/mysql
#        command:
#            - "--default-authentication-plugin=mysql_native_password"
#            - "--lower_case_table_names=1"
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: sf4
#            MYSQL_USER: sf4
#            MYSQL_PASSWORD: sf4

    #PHP-MyAdmin MYSQL
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin_container
#        environment:
#          PMA_HOST: mysql
#          PMA_PORT: 3306
#        ports:
#            - 9091:80
#        links:
#            - mysql

#    #Mail_Host
#    maildev:
#        image: djfarrelly/maildev
#        container_name: maildev_container
#        ports:
#          - 9092:80
